# Generated by Django 5.0.2 on 2024-02-14 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionlistings_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='auction_id',
            new_name='auction',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='auctionlistings',
            name='current_bid',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='auction_id',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bids',
            name='auction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auctionlistings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bids',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
