# Generated by Django 5.0.2 on 2024-02-14 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_auction_id_comments_auction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='time',
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_auctions', to=settings.AUTH_USER_MODEL),
        ),
    ]
