# Generated by Django 5.0.2 on 2024-02-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_comments_creation_date_remove_comments_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='winner',
        ),
    ]
