# Generated by Django 5.0.2 on 2024-02-15 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auctionlistings_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
