# Generated by Django 5.0.1 on 2024-02-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctionlistings_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlistings',
            old_name='state',
            new_name='active',
        ),
    ]
