# Generated by Django 5.0.1 on 2024-02-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_state_auctionlistings_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlistings',
            old_name='image',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
