# Generated by Django 5.0.2 on 2024-02-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_comments_auction_alter_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
