# Generated by Django 5.0.1 on 2024-02-08 11:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_image_auctionlistings_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
