# Generated by Django 5.0.2 on 2024-02-24 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctionlistings_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='current_bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winning_auctions', to='auctions.bids'),
        ),
    ]
