# Generated by Django 5.0.2 on 2024-02-24 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auctionlistings_current_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlistings',
            old_name='starting_bid',
            new_name='starting_price',
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='current_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winning_auctions', to='auctions.bids'),
        ),
    ]
