# Generated by Django 5.0.1 on 2024-02-09 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auctionlistings_users_watching'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auctions.categories'),
        ),
    ]
